A = csvread('matA.output');
Cext = csvread('Cext.output');
Xext = csvread('Xext.output');
Yext = csvread('Yext.output');
inverse_A=inv(A);
Xint = inverse_A * Cext * Xext;
Yint = inverse_A * Cext * Yext;
formatSpec='%f\n';
fileID = fopen('Xint.output','w');
fprintf(fileID,formatSpec,Xint);
fileID = fopen('Yint.output','w');
fprintf(fileID,formatSpec,Yint);