find_file(UMFPACK_H umfpack.h)
find_library(UMFPACK_LIBRARY umfpack)
set(HAVE_UMFPACK false)
if(UMFPACK_H AND UMFPACK_LIBRARY)
	get_filename_component(UMFPACK_INCLUDE_DIRS ${UMFPACK_H} PATH)
	find_library(AMD_LIBRARY amd)
	find_library(BLAS_LIBRARY blas)
	if(AMD_LIBRARY AND BLAS_LIBRARY)
		set(UMFPACK_LIBRARIES "${UMFPACK_LIBRARY};${AMD_LIBRARY};${BLAS_LIBRARY}")
		set(HAVE_UMFPACK true)
	endif()
endif()
